# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f430a7105f886e1d2bb1978e719f8d4a5e3fccced81f213d0bdcef87a1c5e1ada6916812000b81891641622715955e7c15f3cba6c209117e925129eefdb26437

test:
  secret_key_base: 18f0ce79c93a979b6dde6ad21277428935cc26add579f777444ed7f232d70df191151f0cb1a8e1119dd35efe63c24f2aa93a13491ba48a342e8edd9fe03774fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
